### ISSUE TITLE
Windows Defender Threat Found

### ISSUE THREAD

**Issue by MaximusR9** [loljoshie/lj-loading#1]
I don't why but every time I try to download the latest version of lj-loading and lj-hud I get a threat found message.

![image](https://user-images.githubusercontent.com/49029210/145393196-1f56ca6d-cc1e-414c-9c89-f38e04d0c55e.png)

I tried downloading old version of lj-loading and it worked fine without any threat found message.

**Comment by loljoshie** [comment]
Very strange really don't have an answer. All I can say is there's no threat, and no one else I know has been getting that. But I'll do some digging and see if I can get the same result.

**Comment by MaximusR9** [comment]
I tried downloading it again and it didn't give any threat message now so it was probably a false detection by windows defender, your scripts are 100% safe and they are open source so anyone can look at the source code :)
